### PR TITLE
Reorganize directories

### PR DESCRIPTION
**Pull request by jadephilipoom**
For #893 

This simplifies our dependency structure so that we can run the cava2 and HMAC work on CI without having strange dependencies like the cava2 core library depending on the HMAC specification. It also updates the CI so that everything in cava2, plus the newly-relocated HMAC-specific circuits and firmware, is now checked.

The dependency graph now looks like:
```
{examples,tests,demos,silveroak-opentitan/pinmux,silveroak-opentitan/aes} <-- cava
cava2 <-- cava (for Util)
firmware <-- cava (for Util), cava2 (preemptive, for #904)
silveroak-opentitan/hmac <-- cava (for Util), cava2, firmware
```
One clear further simplification we could make here is to separate `cava/Util` into its own directory, so that we have:
```
cava <-- util
cava2 <-- util
{examples,tests,demos,silveroak-opentitan/pinmux,silveroak-opentitan/aes} <-- util, cava
firmware <-- util, cava2
silveroak-opentitan/hmac <-- util, cava2, firmware
```
This might be a good follow-up PR; it would make the CI run faster by not requiring that we wait for the entire `cava` directory to build before starting `cava2` or `firmware`.

### CODE REVIEW

**Comment by jadephilipoom** [comment]
FYI: The names of some required checks have changed (`make_directories (examples)` and `make_directories (tests)`), so I'm going to temporarily un-require those in the repository settings until this is merged, then add them back with the new names.

**Comment by blaxill** [comment]
CI:

```
make[2]: Entering directory '/home/runner/work/silveroak/silveroak/silveroak-opentitan/hmac/hw'
COQDEP VFILES
make[3]: *** No rule to make target '../../../cava2/Types.vo', needed by 'Hmac.vo'.  Stop.
```

I see the `needs: [make_cava, make_cava2 ...` in the CI yaml file, is the path in the Makefile/_CoqProject incorrect?

**Comment by jadephilipoom** [comment]
> I see the `needs: [make_cava, make_cava2 ...` in the CI yaml file, is the path in the Makefile/_CoqProject incorrect?

It works locally (will still clean out old build files and try again to double-check), so I think the path is right. I'll try fiddling with the CI a bit. Will move this to draft until I get it working.

**Comment by jadephilipoom** [comment]
Fixed now!

**Review by blaxill — APPROVED** [review]
Lgtm! Thanks Jade

**Comment by jadephilipoom** [comment]
The `examples` and `tests` checks have now been re-enabled with the new names.

**Pull request merged**
