### PR TITLE
Add SystemVerilog testbench for bitonic sorter

### PR DESCRIPTION
**Pull request by satnam6502**
Also discard empty vectors when generating SystemVerilog.
Test passes!
```
clang++ -L/usr/local/opt/sqlite/lib    bsort4_8_tb.o verilated.o verilated_vcd_c.o Vbsort4_8_tb__ALL.a    -o Vbsort4_8_tb -lm -lstdc++
obj_dir/Vbsort4_8_tb
                  10: tick = 0,  inputs[0] = 12,  inputs[1] = 2,  inputs[2] = 11,  inputs[3] = 10,  inputs[4] = 16,  inputs[5] = 14,  inputs[6] = 6,  inputs[7] = 3,  inputs[8] = 5,  inputs[9] = 1,  inputs[10] = 7,  inputs[11] = 15,  inputs[12] = 9,  inputs[13] = 13,  inputs[14] = 4,  inputs[15] = 8, 
                                 sorted[0] = 1,  sorted[1] = 2,  sorted[2] = 3,  sorted[3] = 4,  sorted[4] = 5,  sorted[5] = 6,  sorted[6] = 7,  sorted[7] = 8,  sorted[8] = 9,  sorted[9] = 10,  sorted[10] = 11,  sorted[11] = 12,  sorted[12] = 13,  sorted[13] = 14,  sorted[14] = 15,  sorted[15] = 16
PASSED
```
CC: @smore-lore

### CODE REVIEW

**Comment by satnam6502** [comment]
Why did a bunch of other files get added to this PR? I only changed a few files in the `test` directory.

**Comment by satnam6502** [comment]
@blaxill Is this a CI error?

**Comment by blaxill** [comment]
> @blaxill Is this a CI error?
> 
> ```
> COQC src/RecordUpdate.v
> COQTEST tests/RegressionTests.v (ref: tests/RegressionTests.ref)
> --- tests/RegressionTests.ref	2021-03-25 06:49:53.446521891 +0000
> +++ /tmp/tmp.gEkgPdBwvm	2021-03-25 06:54:48.082695377 +0000
> @@ -1,8 +1,8 @@
>  The command has indeed failed with message:
> -Unable to satisfy the following constraints:
> make[5]: *** [Makefile.coq.local:23: tests/RegressionTests.vo] Error 1
> -In environment:
> -r : X
> -a : nat
> make[4]: *** [Makefile.coq:339: all] Error 2
> -
> make[3]: *** [Makefile:9: all] Error 2
> make[2]: *** [Makefile:40: build-record-update] Error 2
> -?Setter : "Setter getA"
> -
> +The following term contains unresolved implicit arguments:
> make[1]: *** [Makefile:55: record-update] Error 2
> make: *** [Makefile:37: third_party] Error 2
> +  (fun (r : X) (a : nat) => r <| getA ::= (fun _ : nat => a) |>)
> +More precisely: 
> +- ?Setter: Cannot infer the implicit parameter Setter of set whose type is
> +  "Setter getA" (no type class instance found) in environment:
> +  r : X
> +  a : nat
> ```
> 
> And why do I see this and what does it mean?
> 
> ```
> 	modified:   third_party/coq-record-update (new commits)
> ```

`coq-record-update` is a submodule that was recently updated. Unlike regular files, git does not apply updates to submodules and so to update it you need to run `git submodule update --recursive` or `cd third_party; make update`. The CI error occurs because without updating locally but `git add`ing the `coq-record-update` directory you are effectively downgrading the submodule but the latest version is required to work with the latest CI version of Coq. Specifically the error is a regression test in `coq-record-update` that is over-specific and fixed in more recent versions.

To make CI easier, one changes recently removed submodule update from third_party make default target. My rationale is that the submodules update infrequently, and updates to submodules are visible in the usual `git status` as dirty third_party directories. I don't mind reverting that change though as I'm getting the hang of github actions now.

> Why did a bunch of other files get added to this PR?

I don't think we've ever had gitignore's for the binary `AESSV` or `.swp` files. We could add `AESSV` to gitignore, and also `.swp`, but in general ignoring editor specific files would be better suited to a git-global `gitignore` specific to you.

**Comment by blaxill** [comment]
We could also alternatively add a `post-checkout` hook that runs `git submodule update`

**Comment by satnam6502** [comment]
Remade

**Pull request closed without merging**
