### PR TITLE
Performance comparison of OT top-level block vs. Silver Oak

### PR DESCRIPTION
**Pull request by satnam6502**
Issue #469

### CODE REVIEW

**Review by blaxill — APPROVED** [review]
LGTM

> For the final analysis we need to complete the implementation fo the AES control block.

FWIW, at least initially we won't support 128/192 AES (only 256) which should mean we will use less resources.

**Comment by satnam6502** [comment]
> LGTM
> 
> > For the final analysis we need to complete the implementation fo the AES control block.
> 
> FWIW, at least initially we won't support 128/192 AES (only 256) which should mean we will use less resources.

Noted. I keep forgetting about this.

**Comment by satnam6502** [comment]
W

> > LGTM
> > > For the final analysis we need to complete the implementation fo the AES control block.
> > 
> > 
> > FWIW, at least initially we won't support 128/192 AES (only 256) which should mean we will use less resources.
> 
> Noted. I keep forgetting about this.

Perhaps we can easily tweak the OT design to remove the 128/192 behviour.

**Comment by blaxill** [comment]
> W
> 
> > > LGTM
> > > > For the final analysis we need to complete the implementation fo the AES control block.
> > > 
> > > 
> > > FWIW, at least initially we won't support 128/192 AES (only 256) which should mean we will use less resources.
> > 
> > 
> > Noted. I keep forgetting about this.
> 
> Perhaps we can easily tweak the OT design to remove the 128/192 behviour.

The 192 can be disabled through a SystemVerilog parameter (at least the parameter is there, I haven;t tested), 128 would require modification. I'll also try to estimate how much additional work for us to support 128/192

**Pull request merged**
