### PR TITLE
Fix a tiny typo

### PR DESCRIPTION
**Pull request by ju-sh**
Fix a tiny typo

### CODE REVIEW

**Comment by jadephilipoom** [comment]
Thanks for the fix! Do you mind signing the CLA so we can merge it?

**Comment by ju-sh** [comment]
@googlebot I signed it!

**Comment by ju-sh** [comment]
Was sort of thinking that cla wasn't needed for typo fixes (since the bot probably kicks in by default).

**Comment by jadephilipoom** [comment]
> Was sort of thinking that cla wasn't needed for typo fixes (since the bot probably kicks in by default).

It does, but the repo is set up so I can't merge it until that automatic check passes. Thanks for taking the trouble!

**Pull request merged**
