### PR TITLE
Sketch of desired Cava API for loop and delay

### PR DESCRIPTION
**Pull request by satnam6502**
WIP sketch for the API I think we need to have for loops and delay in Cava for a viable release candidate.

### CODE REVIEW

**Comment by satnam6502** [comment]
@jadephilipoom @blaxill why do I have to fully qualify `ExtLib.Structures.MonadState.put` and `ExtLib.Structures.MonadState.get` here? I get an error if I don't fully qualify them. This seems odd because the import statement is there... and that's exactly how I import them from `MonadState` in the main Cava code. Thank you.

**Comment by jadephilipoom** [comment]
> @jadephilipoom @blaxill why do I have to fully qualify `ExtLib.Structures.MonadState.put` and `ExtLib.Structures.MonadState.get` here? I get an error if I don't fully qualify them. This seems odd because the import statement is there... and that's exactly how I import them from `MonadState` in the main Cava code. Thank you.

Sounds like something else in context is called `put`/`get`. What is the output of `Locate put`?

**Comment by blaxill** [comment]
> @jadephilipoom @blaxill why do I have to fully qualify `ExtLib.Structures.MonadState.put` and `ExtLib.Structures.MonadState.get` here? I get an error if I don't fully qualify them. This seems odd because the import statement is there... and that's exactly how I import them from `MonadState` in the main Cava code. Thank you.

You're importing the concrete instance from __`Data.Monads.StateMonad`__ but, as you note, the class and its methods are defined in __`Structures.MonadState`__, if you add `Require Import ExtLib.Structures.MonadState.` they will work without qualification.

**Comment by satnam6502** [comment]
> > @jadephilipoom @blaxill why do I have to fully qualify `ExtLib.Structures.MonadState.put` and `ExtLib.Structures.MonadState.get` here? I get an error if I don't fully qualify them. This seems odd because the import statement is there... and that's exactly how I import them from `MonadState` in the main Cava code. Thank you.
> 
> You're importing the concrete instance from **`Data.Monads.StateMonad`** but, as you note, the class and its methods are defined in **`Structures.MonadState`**, if you add `Require Import ExtLib.Structures.MonadState.` they will work without qualification.

Thank you! Fixed.

**Pull request merged**
