### PR TITLE
Acorn SubBytes: definition + test

### LINKED ISSUE #320: Make Acorn implementation of sub_bytes

### PR DESCRIPTION
**Pull request by smore-lore**
For now, porting over LUT-based implementation from sub bytes.

Still working on here - 'reflexivity' proofs in AES256Equivalence.v hang.

Closes #320

### CODE REVIEW

**Comment by satnam6502** [comment]
I assume the issues in the comments still stand.
```coq
  (* two problems:
     - nat_to_bitvec_sized returns a bitvec in the opposite direction we want
        (e.g. instead of [T, F, T, F....F], we get [F...F, T, F, T].
     - indexAt is taking an index where the bits need to be mirrored
     - using 'rev' to achieve this is so slow, it causes the computation to not be finished
   *)
```

**Comment by smore-lore** [comment]
Sorry - those are fixed. Will remove them. The remaining issue is just with AES256Equivalence.

**Review by jadephilipoom — APPROVED** [review]
LGTM!

**Comment by jadephilipoom** [comment]
As I said over email, let's merge this PR without fixing the `AESEquivalence` proofs. Feel free to create an issue and assign it to me, and I'll take a look shortly.

**Comment by blaxill** [comment]
Thanks for the PR, I'm going to go ahead and merge this so I can extract a netlist from it.

**Pull request merged**
