### PR TITLE
Merge main into gh-pages

### PR DESCRIPTION
**Pull request by jadephilipoom**
Redoing #632 (and adding the changes to `main` since), having learned the lesson to rebase instead of squash!

### CODE REVIEW

**Review by blaxill — COMMENTED** [review]
I think it would be best to keep `gh-pages` clear of code and add `main` as a submodule if needed. If we go down that route, do you want to merge this in the meantime?

**Comment by jadephilipoom** [comment]
Looks like we'll definitely have to go the other route. I can't merge this PR without squashing (rebasing has conflicts and merge commits are disallowed), which would just put us in the same position for the next merge. Created #644 to track this task.

I'm going to see if I can create the new repo quickly; if I can, I'll just close this. If it seems like it might take a while, I'll squash + merge this PR and push the updates to the tutorial that I have locally, so that they can be up while we wait on further setup. Does that sound reasonable?

**Comment by blaxill** [comment]
Yep sounds good to me!

**Review by satnam6502 — APPROVED** [review]

**Comment by jadephilipoom** [comment]
Closing in favor of #649 (see discussion on #644)

**Pull request closed without merging**
