### PR TITLE
Define a mux2 library element that works over pairs

### PR DESCRIPTION
**Pull request by satnam6502**
@jadephilipoom Why do I now need to add `(A:=Bit)` in the `MuxExamples.v` tests file below?
A stepping stone towards rationalizing the instances of `mux2`-like things in our rep. #450

### CODE REVIEW

**Comment by blaxill** [comment]
Perhaps remove the existing mux2 ?

**Comment by satnam6502** [comment]
> Perhaps remove the existing mux2 ?

I was doing it a step at a time. I had planned to assign an issue to others to remove the existing muxes, update proofs etc.

**Comment by satnam6502** [comment]
@jadephilipoom another note abut the test is `MuxExamples`. There are four test vectors that are used to test `mux2` with four separate test invocations. In a subsequent PR I plan to make this just one test invocation since now the `mux2` circuit can take a stream of inputs i.e. we can just supply the four test vectors in sequence to the circuit and check the four test outputs in one test.

**Review by blaxill — APPROVED** [review]
Lgtm!

**Comment by jadephilipoom** [comment]
> @jadephilipoom Why do I now need to add (A:=Bit) in the MuxExamples.v tests file below?

The previous `mux2_1` was already specialized to `signal Bit`, while the new one is for any `SignalType`. To the Coq type unification, the two problems look like:

with `mux2_1` : `combType Bit = bool`
with generic `mux2` : `combType ?t = bool`

The first one can be resolved by just unfolding `combType`. For the second, though, Coq would have to figure out that it can instantiate the `?t` with `Bit`, which is a much harder problem. By passing the explicit argument you plug in `t` yourself. An alternate solution is that if `true` and `false` were coerced to `combType Bit`, the problem would be `combType ?t = combType Bit`, which Coq would also figure out.

**Comment by satnam6502** [comment]
> > @jadephilipoom Why do I now need to add (A:=Bit) in the MuxExamples.v tests file below?
> 
> The previous `mux2_1` was already specialized to `signal Bit`, while the new one is for any `SignalType`. To the Coq type unification, the two problems look like:
> 
> with `mux2_1` : `combType Bit = bool`
> with generic `mux2` : `combType ?t = bool`
> 
> The first one can be resolved by just unfolding `combType`. For the second, though, Coq would have to figure out that it can instantiate the `?t` with `Bit`, which is a much harder problem. By passing the explicit argument you plug in `t` yourself. An alternate solution is that if `true` and `false` were coerced to `combType Bit`, the problem would be `combType ?t = combType Bit`, which Coq would also figure out.

Perhaps the way I should write this test is to first declare a specialized version of `muxPair`, say `mux2_1`, and then use it in the tests.

**Pull request merged**
